name: real_time_pipeline
version: 1.0.0

profile: default

models:
  real_time_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
      +on_schema_change: append_new_column