default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      port: 5432
      dbname: {{ env_var('POSTGRES_DB') }}
      schema: public